### PR TITLE
Fixing ix_hands setting non-standard c_hands in t_pose

### PR DESCRIPTION
**Pull request by OffLegAz**
I created this request cause' I had a problem with setting custom hands to some factions. The thing is - the custom hands were not from GMod, they were installed as the addon.

### CODE REVIEW

**Comment by OffLegAz** [comment]
I found a bug. Besides **ACT_VM_FISTS_DRAW** set to '2' and **ACT_VM_FISTS_HOLSTER** to '1',
in the console, if you print them, you will get the numbers of '3' and '2'.

But if you then resave ix_hands file the values will change to which are set in this file. I supose that these two global variables are set somewhere else, but I can't find where.

**Comment by impulsh** [comment]
You should be setting up the corresponding hands for your models in your schema, like in https://github.com/NebulousCloud/helix/blob/master/gamemode/shared.lua#L161

**Comment by OffLegAz** [comment]
I set them just like in **’shared.lua’** file, but as I said, with the original code if you define for your model hands which are not standard you’ll get them t-posing without animation. So, I’ve tried to deal with it.

**Comment by OffLegAz** [comment]
Like if you set something like that:
`player_manager.AddValidModel("vortigaunt", "models/vortigaunt.mdl")
player_manager.AddValidHands("vortigaunt", "models/weapons/c_arms_chell.mdl", 0, "0000000")
`

It would work fine. But if you just change hands to non-standard like that:
`player_manager.AddValidModel("vortigaunt", "models/vortigaunt.mdl")
player_manager.AddValidHands("vortigaunt", "models/hands_vortigaunt_free.mdl", 0, "0000000")
`
You'll get them in t-pose.

**Pull request merged**
