### PR TITLE
Fix server error upon using vendors.

### LINKED ISSUE #34: Vendor errors on the server when used.
A standard vendor when spawned on the skeleton schema has this error on the server.

> [ERROR] lua/includes/util.lua:204: attempt to index a string value with bad key ('IsValid' is not part of the string library)
>   1. error - [C]:-1
>    2. __index - lua/includes/extensions/string.lua:297
>     3. IsValid - lua/includes/util.lua:204
>      4. Get - gamemodes/helix/gamemode/core/libs/sh_option.lua:250
>       5. text - gamemodes/helix/gamemode/core/libs/sh_language.lua:30
>        6. Parse - gamemodes/helix/gamemode/core/libs/sh_log.lua:44
>         7. Add - gamemodes/helix/gamemode/core/libs/sh_log.lua:64
>          8. unknown - gamemodes/helix/plugins/vendor/entities/entities/ix_vendor.lua:215

### PR DESCRIPTION
**Pull request by sannysc**
This fixes #34 where a server error occurs upon using a vendor.

### CODE REVIEW

**Comment by alexgrist** [comment]
Ah, this fix was already in our other repo but must've missed it when mirroring.

**Comment by sannysc** [comment]
I see, but without knowing when you guys plan on releasing the update, I think it's harmful to have solutions for known issues go unimplemented. I get where you're coming from, though. I am just afraid this whole update will make people hesitant to contribute. I know it's like that for me. Luckily this was a simple change.

Feel free to close.

**Comment by alexgrist** [comment]
As I said, I must've missed it when mirroring non-UI changes to the public repo.

**Comment by sannysc** [comment]
Oh I think I misunderstood what you meant originally.

**Pull request merged**
