### PR TITLE
Fix Items not destroying when damaged, add a 'weight' display to item…

### PR DESCRIPTION
**Pull request by ZeMysticalTaco**
…s on the ground.

The display is right above the item name, I wasn't sure where else to put it without disturbing the positions of the other text strings.

### CODE REVIEW

**Comment by impulsh** [comment]
I feel that adding text for the width/height of the item would introduce some unnecessary clutter. Is there any reason why the player would need to know the size of the item before interacting with it?

**Comment by ZeMysticalTaco** [comment]
It doesn't tell you the size of an item when you try to pick it up and your inventory is full. That's pretty much the only use for it, it could be adjusted so that the notify for the item pickup is changed to have the width height, but that just doesn't look as pretty: image 

It's just useful end user content.

**Comment by alexgrist** [comment]
Yeah, I definitely get the reason this would be useful; Not sure if there's a better way to give that feedback though.

**Comment by ZeMysticalTaco** [comment]
I can't see any way off the top of my head to express it better, honestly.

**Comment by alexgrist** [comment]
Adding it to the notification is way better imo.

I think it'd be better to just merge the fix and then decide whether to display it on the target info or notify after.

**Comment by Johnny7A2** [comment]
Hello,

I think it's better adding it to the item info, just because a player may be more "attentive" to the item itself than a passing notification.

Idk, just saying my opinion.

**Comment by impulsh** [comment]
The notify is something that we should definitely have as we don't currently have any feedback for failed item pickups. I do agree on displaying the item size, but we'll need to find a way to display that information that seems a little less "tacked-on" than just displaying `(4x2)` above the name.

If you can commit the notify addition and revert the item text, I'll merge those changes for now.

**Comment by ZeMysticalTaco** [comment]
I don't know if you guys are still doing translation support but, it returns it in English because I just made it originally for demonstration. I haven't looked at the language library at all.

**Comment by impulsh** [comment]
I'll be omitting the size of the item in the phrase since it'll be redundant once there is a proper item size indicator put in

**Pull request merged**
