### PR TITLE
YAML for database configuration

### PR DESCRIPTION
**Pull request by MrMe0w**

### CODE REVIEW

**Comment by sannysc** [comment]
Having a yaml parser is overkill.

I think a much better option for configuration would be something like [this](https://luarocks.org/modules/luarocks/config). That module allows configs to be written in native lua syntax, which is especially useful since this project is made in lua.

**Comment by MrMe0w** [comment]
@sannysc then why not use lua for config?
I had reasons for more than just this particular instance (db config) to suggest a yaml parser, for example a better language phrase organization (like Rails).
Also this yaml library has a single extra function added by me that also reads from .local.yml files, which allows push-to-deploy configurations to have prod config stored in a file without having it in the repo, but that's irrelevant in the context of a reply to your comment. I just felt like pointing it out. And maybe hinting than gmod could use just a little more convention for readable code *wink wink*

**Comment by sannysc** [comment]
It is lua. It loads the config as a lua script with a special environment that doesn't cause indexing errors, so you are free to organize the config in nested tables that you don't have to define in advance.

```lua
this.is.a.valid.configuration = true
without.having.to.define = 100
the.tables.yourself = {1, 2, 3}
which.makes.it.very.easy = "to read and write"
```

https://gist.github.com/sannysc/0f491f08578a063f619e0f09295f9839

And it does it in 46 lines, compared to this yaml parser, which is 605 lines long...
If you want to have production config that isn't included in the repo, then you should use `.gitignore`

No point in even talking about this now since it was already merged. I just wish better alternatives were looked into. Very uncharacteristic for helix to include something like this. It feels like something clockwork would have. A gimmicky library that turns a simple task into something way bigger than it needs to be.

**Comment by alexgrist** [comment]
@sannysc The only other resonable alternative would be to have the typical KeyValuesToTable or whatever it was.

**Pull request merged**
