### PR TITLE
Make use of the status field in MySQL queries

### PR DESCRIPTION
**Pull request by SleepyMode**

### CODE REVIEW

**Comment by alexgrist** [comment]
A database callback assumes success, why run on a failure?

**Comment by SleepyMode** [comment]
Why have the status variable in the first place then?
This just makes it actually be used

**Comment by alexgrist** [comment]
That's mostly a leftover from when the wrapper had tmysql support.

**Comment by impulsh** [comment]
If anything, we should remove `bStatus` and add a failure callback instead.

**Pull request closed without merging**
