### PR TITLE
Update

### PR DESCRIPTION
**Pull request by jellyton69**

### CODE REVIEW

**Comment by garytate** [comment]
This has a lot of missing updates which you've committed with whatever you tried to - and honestly no idea what the pull request is intended to change

**Comment by alexgrist** [comment]
No idea what this PR was supposed to be but whatever it is, you’re doing it wrong.

**Comment by jellyton69** [comment]
Oh my god I'm so sorry, I have no idea how this happened, I was just trying to undo the edits I made to my copy so I could get it back to Vanilla like it's meant to be. I have no idea how I managed to open this pull.

**Comment by alexgrist** [comment]
No problem

**Pull request closed without merging**
