### PR TITLE
snip

### PR DESCRIPTION
**Pull request by alexanderpaulgristhucker**

### CODE REVIEW

**Comment by alexanderpaulgristhucker** [comment]
Accept it, please. It adds hooks for Map Scene add/remove.

**Comment by alexanderpaulgristhucker** [comment]
maybe add this video i think it would Be Funney https://www.youtube.com/watch?v=tM3pHcTGxY0

**Comment by Fedox-die-Ente** [comment]
Alright?

**Comment by alexanderpaulgristhucker** [comment]
> Alright?

I recognize ur name from nulledbb u were asking about anti-map decompilation protection scripts for metro 2033 assembly. funney.

**Pull request closed without merging**
